import { type ReactNode, useMemo, useState } from "react";
import { CalendarDays, ChevronDown, ChevronRight, Clock3, MapPin, Search, ShieldCheck, SlidersHorizontal, Ticket, Users, Zap } from "lucide-react";
import { Link } from "wouter";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { filterAndSortEvents, type DiscoveryEvent } from "@/lib/discovery";

const fallbackEvents: DiscoveryEvent[] = [{
  id: 1,
  name: "TechFest 2026",
  description: "A high-energy night of future-facing talks, live demos, and builder culture.",
  startTime: new Date(Date.now() + 21 * 86400000),
  venueName: "Main Arena",
  venueAddress: "1 Tixify Way, Mumbai",
  capacity: 60,
  availableSeats: 59,
  category: "Technology",
  status: "PUBLISHED",
  slug: "techfest-2026",
}];

function formatDate(value: Date | string) {
  return new Date(value).toLocaleDateString(undefined, { weekday: "short", month: "short", day: "numeric", year: "numeric" });
}

function SelectControl({ label, value, onChange, children }: { label: string; value: string; onChange: (value: string) => void; children: ReactNode }) {
  return <label className="relative block min-w-[145px] flex-1"><span className="mb-2 block text-[10px] font-semibold uppercase tracking-[.16em] text-[#68675d]">{label}</span><select value={value} onChange={(event) => onChange(event.target.value)} className="h-11 w-full appearance-none rounded-xl border border-[#d8d6cc] bg-white px-3 pr-9 text-sm text-[#171814] outline-none transition focus:border-[#7b3ff2] focus:ring-2 focus:ring-[#7b3ff2]/15">{children}</select><ChevronDown className="pointer-events-none absolute bottom-3.5 right-3 h-4 w-4 text-[#68675d]" /></label>;
}

export default function Home() {
  const { data, isLoading } = trpc.events.list.useQuery();
  const rawEvents = (data?.length ? data : fallbackEvents) as DiscoveryEvent[];
  const [search, setSearch] = useState("");
  const [category, setCategory] = useState("all");
  const [dateRange, setDateRange] = useState("any");
  const [availability, setAvailability] = useState("any");
  const [sort, setSort] = useState("soonest");
  const categories = useMemo(() => Array.from(new Set(rawEvents.map((event) => event.category).filter(Boolean))) as string[], [rawEvents]);
  const filteredEvents = useMemo(() => filterAndSortEvents(rawEvents, { search, category, dateRange: dateRange as "any" | "7" | "30", availability: availability as "any" | "available", sort: sort as "soonest" | "latest" | "availability" | "name" }), [availability, category, dateRange, rawEvents, search, sort]);

  return <div className="min-h-screen overflow-hidden bg-[#0e0e0c] text-[#f7f5ef]">
    <header className="relative z-10 mx-auto flex max-w-7xl items-center justify-between px-5 py-6 lg:px-10"><Link href="/" className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#ddff5a] text-[#10110c]"><Ticket className="h-5 w-5" /></div><span className="text-xl font-semibold tracking-[-0.04em]">tixify<span className="text-[#ddff5a]">.</span></span></Link><nav className="hidden items-center gap-8 text-sm text-[#aaa99e] md:flex"><a href="#events" className="transition hover:text-white">Events</a><a href="#promise" className="transition hover:text-white">Why Tixify</a><Link href="/tickets" className="transition hover:text-white">My tickets</Link></nav><Link href="/login"><Button variant="outline" className="border-white/20 bg-white/5 text-white hover:bg-white/10">Sign in <ChevronRight className="ml-1 h-4 w-4" /></Button></Link></header>
    <main>
      <section className="relative mx-auto max-w-7xl px-5 pb-24 pt-16 lg:px-10 lg:pb-32 lg:pt-20"><div className="pointer-events-none absolute -right-32 top-0 h-[32rem] w-[32rem] rounded-full bg-[#ddff5a]/10 blur-3xl" /><div className="pointer-events-none absolute left-1/3 top-1/2 h-72 w-72 rounded-full bg-[#765cff]/10 blur-3xl" /><div className="relative grid gap-16 lg:grid-cols-[1.1fr_.9fr] lg:items-end"><div><div className="mb-8 inline-flex items-center gap-2 rounded-full border border-[#ddff5a]/20 bg-[#ddff5a]/5 px-3 py-1.5 text-xs font-medium uppercase tracking-[0.18em] text-[#ddff5a]"><span className="h-1.5 w-1.5 rounded-full bg-[#ddff5a] shadow-[0_0_12px_#ddff5a]" /> Live inventory, zero guesswork</div><h1 className="max-w-4xl text-6xl font-semibold leading-[.92] tracking-[-0.07em] sm:text-7xl lg:text-[8.5rem]">Make the<br /><span className="text-[#ddff5a]">moment.</span></h1><p className="mt-8 max-w-xl text-lg leading-8 text-[#aaa99e]">Seats move fast. Your booking should not. Tixify keeps every reservation fair, verified, and in sync — even when the room is full.</p><div className="mt-10 flex flex-wrap gap-3"><a href="#events"><Button className="h-12 rounded-full bg-[#ddff5a] px-6 text-[#10110c] hover:bg-[#cfff32]">Explore events <ChevronRight className="ml-2 h-4 w-4" /></Button></a><Link href="/tickets"><Button variant="outline" className="h-12 rounded-full border-white/15 bg-transparent px-6 text-white hover:bg-white/10">View my tickets</Button></Link></div></div><div className="relative hidden min-h-[22rem] lg:block"><div className="absolute right-8 top-8 h-64 w-52 rotate-6 rounded-[2rem] border border-white/15 bg-gradient-to-br from-[#282922] to-[#171815] p-5 shadow-2xl shadow-black/40"><div className="flex items-start justify-between"><span className="text-xs font-medium uppercase tracking-[.2em] text-[#ddff5a]">TIX / 001</span><Zap className="h-4 w-4 text-[#ddff5a]" /></div><div className="mt-20 text-2xl font-semibold tracking-tight">Next<br />up.</div><div className="mt-6 flex items-end justify-between text-[10px] text-[#85857b]"><span>LIVE ACCESS</span><span>2026</span></div></div><div className="absolute bottom-0 left-20 h-48 w-60 -rotate-6 rounded-[2rem] border border-[#ddff5a]/20 bg-[#ddff5a] p-6 text-[#10110c] shadow-2xl shadow-[#ddff5a]/10"><div className="flex items-center justify-between"><span className="text-xs font-semibold uppercase tracking-[.2em]">Seat map</span><span className="text-xs">A — C</span></div><div className="mt-10 grid grid-cols-6 gap-2">{Array.from({ length: 18 }).map((_, i) => <span key={i} className={`h-3 rounded-full ${i === 7 || i === 12 ? "bg-[#10110c]" : "bg-[#a6c33e]"}`} />)}</div><p className="mt-8 text-xs font-medium">Every seat, accounted for.</p></div></div></div></section>
      <section id="events" className="bg-[#f7f5ef] px-5 py-20 text-[#171814] lg:px-10 lg:py-28"><div className="mx-auto max-w-7xl"><div className="mb-10 flex flex-wrap items-end justify-between gap-6"><div><p className="mb-3 text-xs font-semibold uppercase tracking-[.2em] text-[#68675d]">On the calendar</p><h2 className="text-4xl font-semibold tracking-[-.06em] sm:text-6xl">Find your<br /><span className="text-[#7b3ff2]">next thing.</span></h2></div><span className="text-sm text-[#68675d]">{isLoading ? "Loading live events…" : `${filteredEvents.length} of ${rawEvents.length} event${rawEvents.length === 1 ? "" : "s"}`}</span></div>
        <div className="rounded-[1.5rem] border border-[#dedcd2] bg-[#eeece5] p-4 sm:p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-end"><label className="block flex-[1.4]"><span className="mb-2 block text-[10px] font-semibold uppercase tracking-[.16em] text-[#68675d]">Search events</span><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-[#aaa99e]" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Try TechFest or Mumbai" className="h-11 w-full rounded-xl border border-[#d8d6cc] bg-white pl-10 pr-3 text-sm outline-none transition placeholder:text-[#aaa99e] focus:border-[#7b3ff2] focus:ring-2 focus:ring-[#7b3ff2]/15" /></div></label><SelectControl label="Category" value={category} onChange={setCategory}><option value="all">All categories</option>{categories.map((item) => <option key={item} value={item}>{item}</option>)}</SelectControl><SelectControl label="Date" value={dateRange} onChange={setDateRange}><option value="any">Any date</option><option value="7">Next 7 days</option><option value="30">Next 30 days</option></SelectControl><SelectControl label="Seats" value={availability} onChange={setAvailability}><option value="any">Any availability</option><option value="available">Seats available</option></SelectControl><SelectControl label="Sort by" value={sort} onChange={setSort}><option value="soonest">Soonest</option><option value="latest">Latest</option><option value="availability">Most seats</option><option value="name">Name A–Z</option></SelectControl></div><div className="mt-4 flex items-center gap-2 text-xs text-[#68675d]"><SlidersHorizontal className="h-3.5 w-3.5 text-[#7b3ff2]" /> Filters update live against current event inventory.</div></div>
        <div className="mt-6 grid gap-5 lg:grid-cols-2">{filteredEvents.length ? filteredEvents.map((event) => <Link key={event.id} href={`/events/${event.id}`} className="group"><article className="relative overflow-hidden rounded-[2rem] border border-[#dedcd2] bg-white p-6 transition duration-300 hover:-translate-y-1 hover:border-[#7b3ff2]/40 hover:shadow-2xl hover:shadow-[#7b3ff2]/10 sm:p-8"><div className="absolute right-0 top-0 h-40 w-40 rounded-full bg-[#ddff5a]/40 blur-3xl transition group-hover:bg-[#ddff5a]/70" /><div className="relative flex items-start justify-between"><span className="rounded-full bg-[#f1f0e9] px-3 py-1 text-xs font-semibold uppercase tracking-[.16em]">{event.category ?? "Featured"}</span><span className="grid h-11 w-11 place-items-center rounded-full bg-[#171814] text-white transition group-hover:bg-[#7b3ff2]"><ChevronRight className="h-5 w-5" /></span></div><div className="relative mt-16"><h3 className="max-w-md text-3xl font-semibold tracking-[-.05em] sm:text-4xl">{event.name}</h3><p className="mt-3 max-w-lg text-sm leading-6 text-[#68675d]">{event.description}</p><div className="mt-8 flex flex-wrap gap-4 border-t border-[#eeece5] pt-5 text-sm text-[#68675d]"><span className="inline-flex items-center gap-2"><CalendarDays className="h-4 w-4 text-[#7b3ff2]" /> {formatDate(event.startTime)}</span><span className="inline-flex items-center gap-2"><MapPin className="h-4 w-4 text-[#7b3ff2]" /> {event.venueName}</span><span className={`inline-flex items-center gap-2 font-medium ${Number(event.availableSeats ?? 0) > 0 ? "text-[#526b16]" : "text-[#935b16]"}`}><Users className="h-4 w-4" /> {Number(event.availableSeats ?? 0) > 0 ? `${event.availableSeats} seats left` : "Sold out"}</span></div></div></article></Link>) : <div className="rounded-[2rem] border border-dashed border-[#c7c5b9] p-12 text-center lg:col-span-2"><p className="text-lg font-medium">No events match those filters.</p><p className="mt-2 text-sm text-[#68675d]">Try widening the date range or clearing the search.</p><Button variant="outline" onClick={() => { setSearch(""); setCategory("all"); setDateRange("any"); setAvailability("any"); }} className="mt-6 rounded-full border-[#c7c5b9]">Clear filters</Button></div>}</div></div></section>
      <section id="promise" className="mx-auto max-w-7xl px-5 py-20 lg:px-10 lg:py-28"><div className="grid gap-14 lg:grid-cols-[.8fr_1.2fr]"><div><p className="mb-3 text-xs font-semibold uppercase tracking-[.2em] text-[#ddff5a]">The Tixify promise</p><h2 className="text-4xl font-semibold leading-tight tracking-[-.06em] sm:text-5xl">Calm in the<br /><span className="text-[#aaa99e]">rush.</span></h2></div><div className="grid gap-8 sm:grid-cols-3">{[[ShieldCheck, "Fair by design", "Server-side reservations keep seats from being double-booked."], [Clock3, "Five minute hold", "A clear countdown gives you time to check out without stress."], [Zap, "Instant sync", "Live seat updates keep every screen honest in the room."]].map(([Icon, title, text]) => <div key={title as string} className="border-t border-white/15 pt-5"><Icon className="h-5 w-5 text-[#ddff5a]" /><h3 className="mt-7 text-lg font-medium">{title as string}</h3><p className="mt-3 text-sm leading-6 text-[#aaa99e]">{text as string}</p></div>)}</div></div></section>
    </main><footer className="border-t border-white/10 px-5 py-8 text-sm text-[#77776d] lg:px-10"><div className="mx-auto flex max-w-7xl items-center justify-between"><span>© 2026 Tixify</span><span>Built for the moment.</span></div></footer>
  </div>;
}
