import { useMemo } from "react";
import { Link, useRoute } from "wouter";
import { CalendarDays, CheckCircle2, Loader2, MapPin, Ticket as TicketIcon } from "lucide-react";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import TicketQr from "@/components/TicketQr";

export default function TicketVerificationPage() {
  const [, params] = useRoute("/ticket/:publicCode");
  const publicCode = params?.publicCode ?? "";
  const query = trpc.publicTickets.get.useQuery({ publicCode }, { enabled: Boolean(publicCode), retry: false });
  const qrValue = useMemo(() => typeof window === "undefined" ? "" : new URLSearchParams(window.location.search).get("qr") ?? "", []);
  const signedVerification = trpc.publicTickets.verify.useQuery({ qrValue }, { enabled: qrValue.length > 20, retry: false });

  if (query.isLoading) return <div className="grid min-h-screen place-items-center bg-[#f7f5ef]"><Loader2 className="h-7 w-7 animate-spin text-[#7b3ff2]" /></div>;
  if (query.isError || !query.data) return <div className="grid min-h-screen place-items-center bg-[#f7f5ef] px-5 text-center"><div><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-[#171814] text-[#ddff5a]"><TicketIcon /></div><h1 className="mt-6 text-3xl font-semibold tracking-[-.06em]">Ticket not found.</h1><p className="mt-3 text-[#68675d]">This QR code is invalid or the ticket is no longer available.</p><Link href="/"><Button className="mt-7 rounded-full bg-[#171814] text-white">Back to Tixify</Button></Link></div></div>;
  const ticket = query.data;
  const ticketUrl = ticket.signedPayload && ticket.signature ? `${window.location.origin}/ticket/${ticket.publicCode}?qr=${encodeURIComponent(`tix1.${ticket.signedPayload}.${ticket.signature}`)}` : `${window.location.origin}/ticket/${ticket.publicCode}`;
  const verificationStatus = qrValue && signedVerification.data ? signedVerification.data.status : "VALID";

  return <div className="min-h-screen bg-[#f7f5ef] text-[#171814]"><header className="mx-auto flex max-w-5xl items-center justify-between px-5 py-6 lg:px-10"><Link href="/" className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#171814] text-[#ddff5a]"><TicketIcon className="h-5 w-5" /></div><span className="text-xl font-semibold tracking-[-.04em]">tixify<span className="text-[#7b3ff2]">.</span></span></Link><span className="text-xs font-semibold uppercase tracking-[.16em] text-[#68675d]">Entrance verification</span></header><main className="mx-auto max-w-3xl px-5 pb-20 pt-12 lg:px-10"><div className="text-center"><div className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-[#ddff5a] text-[#171814]"><CheckCircle2 className="h-8 w-8" /></div><p className="mt-7 text-xs font-semibold uppercase tracking-[.2em] text-[#7b3ff2]">{verificationStatus === "VALID" ? "Verified ticket" : "Ticket status"}</p><h1 className="mt-3 text-5xl font-semibold tracking-[-.07em]">{verificationStatus === "VALID" ? "You’re cleared." : verificationStatus.replaceAll("_", " ")}</h1><p className="mt-4 text-[#68675d]">{verificationStatus === "VALID" ? "Present this screen at the entrance." : "This pass should be checked by an event scanner."}</p></div><section className="mt-12 overflow-hidden rounded-[2rem] bg-[#171814] text-white"><div className="grid gap-8 p-7 sm:grid-cols-[1fr_220px] sm:p-10"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#ddff5a]">{ticket.eventName}</p><h2 className="mt-5 text-3xl font-semibold tracking-[-.05em]">{ticket.publicCode}</h2><div className="mt-8 space-y-4 text-sm text-[#aaa99e]"><div className="flex items-center gap-3"><CalendarDays className="h-4 w-4 text-[#ddff5a]" /> {new Date(ticket.startTime).toLocaleString(undefined, { dateStyle: "full", timeStyle: "short" })}</div><div className="flex items-center gap-3"><MapPin className="h-4 w-4 text-[#ddff5a]" /> {ticket.venueName} · {ticket.venueAddress}</div></div><div className="mt-8 flex items-center justify-between border-t border-white/10 pt-5 text-sm"><span className="text-[#aaa99e]">Seat</span><span className="font-mono text-[#ddff5a]">{ticket.section}{ticket.number} · {ticket.seatType}</span></div></div><div className="rounded-2xl bg-[#ddff5a] p-4"><TicketQr value={ticketUrl} size={190} /><p className="mt-3 text-center text-[10px] font-semibold uppercase tracking-[.18em] text-[#171814]">Signed pass</p></div></div><div className="border-t border-white/10 px-7 py-5 text-xs text-[#aaa99e] sm:px-10">Ticket status: <span className="font-semibold text-[#ddff5a]">{ticket.status}</span> · Booking #{ticket.bookingId}</div></section></main></div>;
}
