import { Link } from "wouter";
import { ArrowRight, CalendarDays, LogIn, MapPin, Ticket as TicketIcon } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";

export default function TicketsPage() {
  const { user, loading } = useAuth();
  const { data: tickets = [], isLoading } = trpc.tickets.mine.useQuery(undefined, { enabled: Boolean(user), retry: false });
  if (loading) return <div className="grid min-h-screen place-items-center bg-[#f7f5ef]">Loading…</div>;
  if (!user) return <div className="grid min-h-screen place-items-center bg-[#f7f5ef] px-5 text-center"><div><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-[#171814] text-[#ddff5a]"><TicketIcon /></div><h1 className="mt-6 text-3xl font-semibold tracking-[-.06em]">Your tickets live here.</h1><p className="mt-3 text-[#68675d]">Sign in to access your bookings and verified ticket codes.</p><Button onClick={() => startLogin()} className="mt-7 rounded-full bg-[#171814] text-white"><LogIn className="mr-2 h-4 w-4" /> Sign in</Button></div></div>;
  return <div className="min-h-screen bg-[#f7f5ef] text-[#171814]"><header className="mx-auto flex max-w-6xl items-center justify-between px-5 py-6 lg:px-10"><Link href="/" className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#171814] text-[#ddff5a]"><TicketIcon className="h-5 w-5" /></div><span className="text-xl font-semibold tracking-[-.04em]">tixify<span className="text-[#7b3ff2]">.</span></span></Link><Link href="/events/1" className="inline-flex items-center gap-2 text-sm text-[#68675d] hover:text-[#171814]">Browse events <ArrowRight className="h-4 w-4" /></Link></header><main className="mx-auto max-w-6xl px-5 pb-20 pt-10 lg:px-10"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#7b3ff2]">Your wallet</p><h1 className="mt-3 text-5xl font-semibold tracking-[-.07em]">Hey, {user.name?.split(" ")[0] ?? "there"}.</h1><p className="mt-4 text-[#68675d]">Every verified pass, one place.</p></div><Link href="/events/1"><Button className="rounded-full bg-[#ddff5a] text-[#171814] hover:bg-[#cfff32]">Find an event <ArrowRight className="ml-2 h-4 w-4" /></Button></Link></div><div className="mt-12 grid gap-5 md:grid-cols-2">{isLoading ? <div className="text-[#68675d]">Loading tickets…</div> : tickets.length ? tickets.map((ticket) => <article key={ticket.id} className="rounded-[2rem] border border-[#dedcd2] bg-white p-6"><div className="flex items-start justify-between"><div className="grid h-11 w-11 place-items-center rounded-xl bg-[#f0effa] text-[#7b3ff2]"><TicketIcon className="h-5 w-5" /></div><span className="rounded-full bg-[#ddff5a] px-3 py-1 text-xs font-semibold uppercase tracking-[.15em]">{ticket.status}</span></div><h2 className="mt-8 text-2xl font-semibold tracking-[-.05em]">{ticket.eventName}</h2><div className="mt-5 space-y-3 text-sm text-[#68675d]"><div className="flex items-center gap-3"><CalendarDays className="h-4 w-4 text-[#7b3ff2]" /> {new Date(ticket.startTime).toLocaleString()}</div><div className="flex items-center gap-3"><MapPin className="h-4 w-4 text-[#7b3ff2]" /> {ticket.venueName}</div></div><div className="mt-7 flex items-center justify-between border-t border-[#eeece5] pt-5"><span className="font-mono text-sm text-[#7b3ff2]">{ticket.publicCode}</span><Link href={`/booking/${ticket.bookingId}`}><Button variant="ghost" className="text-[#171814]">Open <ArrowRight className="ml-1 h-4 w-4" /></Button></Link></div></article>) : <div className="rounded-[2rem] border border-dashed border-[#c7c5b9] p-10 text-center text-[#68675d] md:col-span-2">No tickets yet. Your next big moment is one click away.</div>}</div></main></div>;
}
